cc_library(
    name = "json_widget_reader",
    srcs = ["json_widget_reader.cpp"],
    hdrs = ["json_widget_reader.h"],
    deps = [
        "//imcomposer/core/imgui",
        "//third_party/nlohmann",
    ],
    visibility = ["//visibility:public"],
)