cc_library(
    name = "properties",
    srcs = ["properties.cpp"],
    hdrs = ["properties.h"],
    deps = [
        "//imcomposer/core/imgui",
        "//imcomposer/core/fonts",
        "//imcomposer/core/fonts:font_loader",
        "//imcomposer/events",
    ],
    visibility = ["//imcomposer:__subpackages__"],
)
