cc_library(
    name = "toolbar",
    srcs = ["toolbar.cpp"],
    hdrs = ["toolbar.h"],
    deps = [
        "//imcomposer/core/imgui",
        "//imcomposer/core/fonts",
        "//imcomposer/core/fonts:font_loader",
        "//imcomposer/core/file_dialog",
    ],
    visibility = ["//imcomposer:__subpackages__"],
)
