cc_library(
    name = "ui",
    srcs = ["ui.cpp"],
    hdrs = ["ui.h"],
    deps = [
        "//imcomposer/ui/menubar",
        "//imcomposer/ui/toolbar",
        "//imcomposer/ui/canvas",
    ],
    visibility = ["//imcomposer:__subpackages__"],
)
