cc_library(
    name = "fonts",
    srcs = [
        "fonts.h",
    ],
    deps = [
        "//data/fonts/includes",
    ],
    data = [
        "//data/fonts/ttf:fonts",
    ],
    visibility = ["//visibility:public"],
)
