cc_library(
    name = "file_dialog",
    srcs = ["file_dialog.cpp"],
    hdrs = ["file_dialog.h"],
    deps = [
        "//third_party/portable_file_dialogs",
        "//imcomposer/utils:thread",
    ],
    visibility = ["//imcomposer:__subpackages__"],
)