cc_library(
    name = "imgui",
    srcs = [
        "imgui.cpp",
    ],
    hdrs = [
        "imgui.hpp",
    ],
    deps = [
        "//third_party/imgui"
    ],
    visibility = ["//imcomposer:__subpackages__",],
)
