cc_library(
    name = "window",
    srcs = [
        "window.cpp",
    ],
    hdrs = [
        "window.h",
    ],
    deps = [
        "//third_party/glad",
        "//third_party/glfw"
    ],
    visibility = ["//imcomposer:__subpackages__"],
)
