cc_library(
    name = "window",
    srcs = [
        "window.cpp",
    ],
    hdrs = [
        "window.hpp",
    ],
    deps = [
        "//third_party/glad",
        "//third_party/glfw"
    ],
    visibility = ["//imcomposer:__subpackages__", ],
)
