package(default_visibility = ["//imcomposer:__subpackages__"])

cc_library(
    name = "imcomposer",
    srcs = [
        "imcomposer.cpp",
    ],
    hdrs = [
        "imcomposer.hpp"
    ],
    deps = [
        "//imcomposer/lib/core/window",
    ]
)
