package(default_visibility = ["//imcomposer:__subpackages__"])

cc_library(
    name = "imcomposer_ui",
    srcs = [
        "imcomposer_ui.cpp",
    ],
    hdrs = [
        "imcomposer_ui.hpp"
    ],
    deps = [
        "//imcomposer/lib/core/window",
        "//imcomposer/lib/core/imgui"
    ]
)
