cc_library(
    name = "bazel",
    srcs = [
        "bazel.cpp",
    ],
    hdrs = [
        "bazel.h",
    ],
    deps = [
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//imcomposer:__subpackages__",],
)
