cc_library(
    name = "canvas",
    srcs = ["canvas.cpp"],
    hdrs = ["canvas.h"],
    deps = [
        "//imcomposer/core/imgui",
        "//imcomposer/core/fonts",
        "//imcomposer/core/fonts:font_loader",
        "//imcomposer/core/parser:json_widget_reader",
    ],
    visibility = ["//imcomposer:__subpackages__"],
)
