cc_library(
    name = "imgui",
    srcs = [
        "imgui.cpp",
    ],
    hdrs = [
        "imgui.hpp",
    ],
    deps = [
        "//third_party/imgui",
        "//third_party/material_design_icon",
        "//imcomposer/utils:bazel",
    ],
    data = [
        "//third_party/material_design_icon:material_design_icon_font",
    ],
    visibility = ["//imcomposer:__subpackages__",],
)
