cc_library(
    name = "docking",
    srcs = [
        "docking.cpp",
    ],
    hdrs = [
        "docking.hpp"
    ],
    deps = [
        "//imcomposer/core/imgui",
    ],
    visibility = ["//imcomposer:__subpackages__"],
)
