cc_library(
    name = "menubar",
    srcs = ["menubar.cpp"],
    hdrs = ["menubar.h"],
    deps = [
        "//imcomposer/core/imgui",
        "//imcomposer/core/fonts",
        "//imcomposer/core/fonts:font_loader",
    ],
    visibility = ["//imcomposer:__subpackages__"],
)
